paths:
  root_dir: /export/home2/kningtg/WORKSPACE/moment-retrieval/query-moment
  data_dir: /export/home2/kningtg/WORKSPACE/moment-retrieval/data-bin/raw
  cache_dir: /export/home2/kningtg/WORKSPACE/moment-retrieval/data-bin/cache
  work_dir: ${paths.root_dir}/work_dir/${data.dataset}/${flags.exp}
flags:
  debug: false
  ddp: false
  amp: false
  train: true
  wandb: false
  seed: 3147
  exp: mst_detr-v1
data:
  datapipe: mst_detr
  dataset: activitynet
  dataset_dir: ${paths.data_dir}/${data.dataset}
  max_len_video: 512
  target_stride: 4
  word_mask_rate: 0.15
  vid_hdf5: i3d.hdf5
  vid_hdf5_key_template: '{video_id}'
eval:
  ms:
  - 1
  - 5
  ns:
  - 0.3
  - 0.5
  - 0.7
  best_monitor: R1@IoU=0.7
  is_best: max
train:
  num_workers: 8
  num_epochs: 100
  eval_epoch_interval: 1
  batch_size: 32
  optimizer:
    params: null
    lr: 0.0001
    betas:
    - 0.9
    - 0.999
    weight_decay: 0.0001
    _target_: !!python/name:torch.optim.adamw.AdamW ''
  clip_grad: 10.0
  lr_scheduler:
    optimizer: null
    factor: 0.5
    patience: 5
    verbose: true
    _target_: !!python/name:torch.optim.lr_scheduler.ReduceLROnPlateau ''
  val_interval: 1.0
  print_interval: 0.2
model_cfg:
  d_model: 512
  ff_dim: 512
  nhead: 16
  num_layers_enc: 4
  num_layers_dec: 3
  sr_ratio_lvls:
  - 4
  - 4
  - 2
  - 1
  use_patch_merge:
  - true
  - false
  - true
  - true
  dropout: 0.1
  w_iou_loss: 30.0
  w_l1_loss: 10.0
  w_mask_loss: 0.5
  w_enc_aux_loss: 1.0
  w_dec_aux_loss: 1.0
  focal_alpha: 0.1
  sigma_s: 0.21
  sigma_m: 0.25
  topk: 1
model:
  backbone:
    backbone:
      d_model_in: ${model_cfg.d_model}
      d_model_lvls:
        s: '[${model_cfg.d_model}] * ${model_cfg.num_layers_enc}'
        _target_: &id001 !!python/name:kn_util.config.ops.eval_str_impl ''
      num_head_lvls:
        s: '[${model_cfg.nhead}] * ${model_cfg.num_layers_enc}'
        _target_: *id001
      ff_dim_lvls:
        s: '[${model_cfg.d_model}] * ${model_cfg.num_layers_enc}'
        _target_: *id001
      input_vid_dim: 1024
      input_txt_dim: 300
      max_vid_len: 512
      max_txt_len: 100
      sr_ratio_lvls: ${model_cfg.sr_ratio_lvls}
      use_patch_merge: ${model_cfg.use_patch_merge}
      _target_: !!python/name:models.backbone.segformerx.SegFormerX ''
    output_layer:
    - 0
    - 2
    - 3
    intermediate_hidden_size:
    - ${model_cfg.d_model}
    - ${model_cfg.d_model}
    - ${model_cfg.d_model}
    fpn_hidden_size: ${model_cfg.d_model}
    _target_: !!python/name:models.backbone.segformerx.SegFormerXFPN ''
  head:
    d_model: ${model_cfg.d_model}
    nhead: ${model_cfg.nhead}
    ff_dim: ${model_cfg.ff_dim}
    num_query: 100
    num_layers: ${model_cfg.num_layers_dec}
    num_scales: 3
    pooler_resolution: 32
    _target_: !!python/name:models.ms_temporal_detr.ms_temporal_detr.QueryBasedDecoder ''
  model_cfg: ${model_cfg}
  _target_: !!python/name:models.ms_temporal_detr.ms_temporal_detr.MultiScaleTemporalDetr ''
