_base_:
  - "./runtime.yaml"
  - "./pipelines/default.yaml"

pipeline_verbose: ${debug}

data:
  dataset: tacos
  dataset_dir: ${data_dir}/${data.dataset}
  vid_feat_type: clip.video.avg.avg
  # upload_vocab_key: glove_vocab
  num_clip: 256
  pretrained: openai/clip-vit-large-patch14-336


train:
  num_epoch: 12
  eval_epoch_interval: 1
  batch_size: 16
  prefetch_factor: 6
  num_workers: 8

  optimizer:
    type: adam_w
    lr: 1e-5
    weight_decay: 0.98
