root_dir: /export/home2/kningtg/WORKSPACE/moment-retrieval/query-moment
data_dir: /export/home2/kningtg/WORKSPACE/moment-retrieval/data-bin/raw
cache_dir: /export/home2/kningtg/WORKSPACE/moment-retrieval/data-bin/cache
work_dir: ${root_dir}/work_dir
debug: false